application/blueprints/learning/__init__.py
from flask import Blueprint, render_template, request, url_for, flash
from application.models import *
import random


learning = Blueprint('learning', __name__, template_folder='templates')


@learning.route('/<level>')
def learning_start(level):
    themes = Theme.query.filter(Theme.level_id == level).all()
    return render_template('/learning/learning_level.html', themes=themes)

@learning.route('/<level>/<theme_id>')
def theme(level, theme_id):
    name = Theme.query.filter(Theme.id == theme_id).first().name
    return render_template('/learning/learning_map.html', level=level, theme_id=theme_id, name=name)

@learning.route('/<level>/<theme_id>/quantities')
def quantities(level, theme_id):
    quantities = Quantity.query.filter(Quantity.theme_id == theme_id).all()
    return render_template('/learning/quantities.html', quantities=quantities, level=level, theme_id=theme_id)

@learning.route('/<level>/<theme_id>/symbols_test')
def symbol_test(level, theme_id):
    q = random.choice(Quantity.query.filter(Quantity.theme_id == theme_id).all())
    questions = random.sample(Quantity.query.filter(Quantity.id != q.id).all(), k=3)
    questions.append(q)
    random.shuffle(questions)   
    return render_template('/learning/symbol_test.html', questions=questions, correct=q, level=level, theme_id=theme_id)

@learning.route('/<level>/<theme_id>/units_test')
def unit_test(level, theme_id):
    q = random.choice(Quantity.query.filter(Quantity.theme_id == theme_id).all())
    questions = random.sample(Quantity.query.filter(Quantity.id != q.id).all(), k=3)
    questions.append(q)
    random.shuffle(questions)   
    return render_template('/learning/unit_test.html', questions=questions, correct=q, level=level, theme_id=theme_id)

@learning.route('/<level>/<theme_id>/formulas')
def formulas(level, theme_id):
    formulas = Formula.query.filter(Quantity.theme_id == theme_id).all()
    return render_template('/learning/formulas.html', formulas=formulas, level=level, theme_id=theme_id)

@learning.route('/<level>/<theme_id>/formuls_test')
def formul_test(level, theme_id):
    f = random.choice(Formula.query.filter(Formula.theme_id == theme_id).all())
    formulas = random.sample(Formula.query.filter((Formula.id != f.id) & (Formula.name != f.name)).all(), k = 3)
    formulas.append(f)
    random.shuffle(formulas)
    return render_template('/learning/formula_test.html', formulas=formulas, correct=f, level=level, theme_id=theme_id)

application/blueprints/learning/templates/learning/base_learning.html
{% extends 'base.html' %}
{% set active_page = 'learning' %}

{% block title %}
    STUDY_HARD Обучение
{% endblock %}

application/blueprints/learning/templates/learning/formula_test.html
{% extends '/learning/base_learning.html' %}

{% block body %}
<div class="container mb-0 justify-content-center">
    <div class="row">
        <div class="header p-4">
            <div class="main-header container-fluid text-center">
                <h1>Учим формулы</h1>
            </div>
        </div>
    </div>
</div>
<div class="container text-center">
    
    
    <p>Выберите формулу</p>
    <p>{{ correct.name }}</p>
    {% for formula in formulas %}
        {% if formula.id == correct.id %}            
            <button type="button" class="btn btn-primary question" onclick=correct()>$${{ formula.formula }}$$</button>
        {% else %}
            <button type="button" class="btn btn-primary question" onclick=incorrect()>$${{ formula.formula }}$$</button>
        {% endif %}
    {% endfor%}
    <div class="container text-center">
        <a href="{{ url_for('learning.theme', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Назад</button></a>
        <a href="{{ url_for('learning.formul_test', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Ещё</button></a>
    </div>
    <div id="correct"></div>
    <div id="incorrect"></div>
</div>

{% endblock %}

application/blueprints/learning/templates/learning/formulas.html
{% extends '/learning/base_learning.html' %}

{% block body %}
<div class="container mb-0 justify-content-center">
    <div class="row">
        <div class="header p-4">
            <div class="main-header container-fluid text-center">
                <h1>Физические величины</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Формула</th>
                </tr>
            </thead>
            <tbody>
            {% for formula in formulas %}
                <tr>
                    <td>{{ formula.name }}</td>
                    <td>$${{ formula.formula }}$$</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="container text-center">
    <a href="{{ url_for('learning.theme', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Назад</button></a>
</div>

{% endblock %}

application/blueprints/learning/templates/learning/learning_level.html
{% extends '/learning/base_learning.html' %}

{% block body %}
    <div class="container mb-0 justify-content-center">
        <div class="row">
            <div class="header p-4">
                <div class="main-header container-fluid text-center">
                    <h1>Портал в мир физики</h1>
                </div>
            </div>
        </div> 
    </div>

    <div class="container mt-0 justify-content-center">
        <div class="row">
            <div class="timeline">
                <div class="level">
                    <ul>
                        {% for theme in themes %}                    
                            <a class="lv" href="{{ url_for('learning.theme', level=theme.level_id, theme_id=theme.id) }}"><li class="theme"><h2>{{ theme.name }}</h2></li></a>
                        {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <a href="{{ url_for('main_page') }}"><button type="button" class="btn btn-primary question">Назад</button></a>
    </div>
{% endblock %}

application/blueprints/learning/templates/learning/learning_map.html
{% extends '/learning/base_learning.html' %}

{% block body %}
<div class="container mb-0 justify-content-center">
    <div class="row">
        <div class="header p-4">
            <div class="main-header container-fluid text-center">
                <h1>{{ name }}</h1>
            </div>
        </div>
    </div> 
</div>
<div class="container mt-0 justify-content-center">
    <div class="row">
        <div class="timeline">
            <div class="level">
                <ul>                   
                    <a class="lv" href="{{ url_for('learning.quantities', level=level, theme_id=theme_id) }}"><li class="theme"><h2>Физические величины</h2></li></a>     
                </ul>
                <ul>                   
                    <a class="lv" href="{{ url_for('learning.symbol_test', level=level, theme_id=theme_id) }}"><li class="theme"><h2>Учим обозначения</h2></li></a>     
                </ul>
                <ul>                   
                    <a class="lv" href="{{ url_for('learning.unit_test', level=level, theme_id=theme_id) }}"><li class="theme"><h2>Учим единицы измерения</h2></li></a>     
                </ul>
                <ul>                   
                    <a class="lv" href="{{ url_for('learning.formulas', level=level, theme_id=theme_id) }}"><li class="theme"><h2>Формулы</h2></li></a>     
                </ul>
                <ul>                   
                    <a class="lv" href="{{ url_for('learning.formul_test', level=level, theme_id=theme_id) }}"><li class="theme"><h2>Учим формулы</h2></li></a>     
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container text-center">
    <a href="{{ url_for('learning.learning_start', level=level) }}"><button type="button" class="btn btn-primary question">Назад</button></a>
</div>
{% endblock %}

application/blueprints/learning/templates/learning/quantities.html
{% extends '/learning/base_learning.html' %}

{% block body %}
<div class="container mb-0 justify-content-center">
    <div class="row">
        <div class="header p-4">
            <div class="main-header container-fluid text-center">
                <h1>Физические величины</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Обозначение</th>
                    <th scope="col">Единицы измерения</th>
                </tr>
            </thead>
            <tbody>
            {% for quantity in quantities %}
                <tr>
                    <td>{{ quantity.name }}</td>
                    <td>$${{ quantity.symbol }}$$</td>
                    <td>$${{ quantity.unit }}$$</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="container text-center">
    <a href="{{ url_for('learning.theme', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Назад</button></a>
</div>

{% endblock %}

application/blueprints/learning/templates/learning/symbol_test.html
{% extends '/learning/base_learning.html' %}

{% block body %}
<div class="container mb-0 justify-content-center">
    <div class="row">
        <div class="header p-4">
            <div class="main-header container-fluid text-center">
                <h1>Учим обозначения</h1>
            </div>
        </div>
    </div>
</div>
<div class="container text-center">
    
    
    <p>Выберите обозначение</p>
    <p>{{ correct.name }}</p>
    {% for question in questions %}
        {% if question.id == correct.id %}            
            <button type="button" class="btn btn-primary question" onclick=correct()>$${{ question.symbol }}$$</button>
        {% else %}
            <button type="button" class="btn btn-primary question" onclick=incorrect()>$${{ question.symbol }}$$</button>
        {% endif %}
    {% endfor%}
    <div class="container text-center">
        <a href="{{ url_for('learning.theme', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Назад</button></a>
        <a href="{{ url_for('learning.symbol_test', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Ещё</button></a>
    </div>
    <div id="correct"></div>
    <div id="incorrect"></div>
</div>

{% endblock %}

application/blueprints/learning/templates/learning/unit_test.html
{% extends '/learning/base_learning.html' %}

{% block body %}
<div class="container mb-0 justify-content-center">
    <div class="row">
        <div class="header p-4">
            <div class="main-header container-fluid text-center">
                <h1>Учим единицы измерения</h1>
            </div>
        </div>
    </div>
</div>
<div class="container text-center">
    
    
    <p>Выберите единицы измерения:</p>
    <p>{{ correct.name }}</p>
    {% for question in questions %}
        {% if question.id == correct.id %}            
            <button type="button" class="btn btn-primary question" onclick=correct()>$${{ question.unit }}$$</button>
        {% else %}
            <button type="button" class="btn btn-primary question" onclick=incorrect()>$${{ question.unit }}$$</button>
        {% endif %}
    {% endfor%}
    <div class="container text-center">
        <a href="{{ url_for('learning.theme', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Назад</button></a>
        <a href="{{ url_for('learning.unit_test', level=level, theme_id=theme_id) }}"><button type="button" class="btn btn-primary question">Ещё</button></a>
    </div>
    <div id="correct"></div>
    <div id="incorrect"></div>
</div>

{% endblock %}